# Generated by Django 3.1 on 2021-11-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_vehicle_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='gif',
        ),
    ]
