# Generated by Django 3.1 on 2021-11-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_remove_vehicle_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='gif',
            field=models.URLField(default=None),
        ),
    ]
