# Generated by Django 3.1 on 2021-11-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0004_vehicle_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='no_of_seats',
            field=models.IntegerField(default=5),
        ),
    ]
