# Generated by Django 3.1 on 2021-11-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0002_vendor_is_mobile_verified'),
        ('showroom', '0005_vehicle_no_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vendor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
