# Generated by Django 3.1 on 2021-11-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_vehicle_vendor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ('created_date',)},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
