# Generated by Django 3.1 on 2021-11-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0007_auto_20211119_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
