# Generated by Django 3.1 on 2021-12-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
    ]
