# Generated by Django 3.1 on 2021-11-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20211115_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='gif',
            field=models.URLField(default='None', max_length=1000),
        ),
    ]
