# Generated by Django 3.1 on 2021-11-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_auto_20211119_1144'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleoffer',
            old_name='discount_offer',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='vehicleoffer',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
    ]
