# Generated by Django 3.1 on 2021-11-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20211129_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleoffer',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Offer in percentage'),
        ),
    ]
