# Generated by Django 3.1 on 2021-11-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
