# Generated by Django 3.1 on 2021-11-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dp',
            field=models.ImageField(blank=True, upload_to='photos/users_dp/'),
        ),
    ]
