# Generated by Django 3.1 on 2021-11-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211113_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
