# Generated by Django 3.1 on 2022-05-18 05:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField(default=5)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 5, 25, 11, 23, 53, 616528))),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TestDriveUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testDrive.slots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
