# Generated by Django 3.1 on 2022-05-06 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField(default=5)),
                ('dates', models.DateTimeField(default=datetime.datetime(2022, 5, 13, 21, 3, 5, 883078))),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.vehicle')),
            ],
        ),
    ]
