# Generated by Django 3.1 on 2022-05-06 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDrive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='dates',
        ),
        migrations.AddField(
            model_name='slots',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 21, 10, 48, 831791)),
        ),
    ]
