# Generated by Django 3.1 on 2022-05-18 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDrive', '0002_auto_20220518_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdriveusers',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='slots',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 11, 34, 23, 160077)),
        ),
    ]
