# Generated by Django 3.1 on 2022-05-18 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDrive', '0004_auto_20220518_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 14, 7, 17, 690768)),
        ),
    ]
