# Generated by Django 3.1 on 2022-05-19 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDrive', '0005_auto_20220518_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdriveusers',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slots',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 15, 26, 21, 984196)),
        ),
    ]
