# Generated by Django 3.1 on 2021-11-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211124_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='house',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_note',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='street',
            new_name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
