# Generated by Django 3.1 on 2021-11-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=1),
        ),
    ]
