# Generated by Django 3.1 on 2021-11-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20211125_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervehicle',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ordervehicle',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
