# Generated by Django 3.1 on 2021-11-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211125_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervehicle',
            name='paid',
            field=models.FloatField(default=0),
        ),
    ]
