# Generated by Django 3.1 on 2021-11-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0003_auto_20211119_1144'),
        ('orders', '0007_ordervehicle_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervehicle',
            name='vendor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Booking Payment pending', max_length=100),
        ),
    ]
