# Generated by Django 3.1 on 2021-11-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordervehicle_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Booking Payment pending', max_length=100),
        ),
    ]
