# Generated by Django 3.1 on 2021-11-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20211126_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordervehicle',
            name='status',
            field=models.CharField(default='Offline verification Pending', max_length=100),
        ),
    ]
